bill/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('gates.urls', namespace="gates")),
    url(r'^admin/', include(admin.site.urls)),
]

gates/urls.py
from django.conf.urls import url

from . import views
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

urlpatterns = [
    # Basic group list and record list
    url(r'^$',
        views.GroupListView.as_view(), name='index'),
    url(r'^group/(?P<pk>[0-9]+)/$',
        views.GroupDetailView.as_view(), name='group'),

    # User auth
    url(r'^accounts/signup/$',
        CreateView.as_view(
            template_name='gates/signup.html',
            form_class=UserCreationForm,
            success_url='/'
        ), name='signup'),
    url(r'^accounts/login/$',
        views.LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$',
        views.LogoutView.as_view(), name='logout'),

    # Group model add/update/delete
    # @yq0283: Change group add url to 'create',
    #          otherwise will cause abnormal behavior in admin-end
    url(r'group/create/$',
        views.GroupCreateView.as_view(), name='group_add'),
    url(r'group/(?P<pk>[0-9]+)/update/$',
        views.GroupUpdateView.as_view(), name='group_update'),
    url(r'group/(?P<pk>[0-9]+)/delete/$',
        views.GroupDeleteView.as_view(), name='group_delete'),

    # Cost model add/update/delete
    url(r'group/(?P<pid>[0-9]+)/cost/add/$',
        views.CostCreateView, name='cost_add'),
    url(r'group/(?P<pid>[0-9]+)/cost/(?P<pk>[0-9]+)/$',
        views.CostUpdateView.as_view(), name='cost_update'),
    url(r'group/(?P<pid>[0-9]+)/cost/(?P<pk>[0-9]+)/delete/$',
        views.CostDeleteView.as_view(), name='cost_delete'),
]

gates/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User


class Group(models.Model):
    name = models.CharField(max_length=100)
    desc = models.CharField(max_length=200)
    members = models.ManyToManyField(User)
    creation_date = models.DateTimeField(auto_now_add=True)
    last_change_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('gates:index')

    @staticmethod
    def get_form_fields():
        return ['name', 'desc']


class Cost(models.Model):
    """
    (payer is not receiver, amount is negative) -->
        Payer pay back to receiver.
    (payer is not receiver, amount is positive) -->
        Receiver need to pay back to payer.
    (payer is receiver, amount has to be positive) -->
        Payer pay for the project, spilting with entire project.
    """
    group = models.ForeignKey(Group)
    name = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    note = models.CharField(max_length=200, blank=True)
    payer = models.ForeignKey(User, related_name='cost_payer')
    receiver = models.ManyToManyField(
        User, related_name='cost_receiver', through='CostDetail')
    creation_date = models.DateTimeField(auto_now_add=True)
    last_change_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cost-detail', kwargs={'pk': self.pk})

    @staticmethod
    def get_form_fields():
        return ['name', 'amount', 'note', 'payer']


class CostDetail(models.Model):
    record = models.ForeignKey(Cost)
    user = models.ForeignKey(User)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    @staticmethod
    def get_form_fields():
        return ['user', 'amount']


class Payment(models.Model):
    group = models.ForeignKey(Group)
    name = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    note = models.CharField(max_length=200, blank=True)
    payer = models.ForeignKey(User, related_name='payment_payer')
    receiver = models.ForeignKey(User, related_name='payment_receiver')
    creation_date = models.DateTimeField(auto_now_add=True)
    last_change_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('payment-detail', kwargs={'pk': self.pk})

    @staticmethod
    def get_form_fields():
        return ['name', 'amount', 'note', 'payer', 'receiver']


class Balance(models.Model):
    """
    nothing here
    """
    group = models.ForeignKey(Group)
    user = models.ForeignKey(User)
    balance = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.group.name + " " + self.user.username + " " \
               + str(self.balance)

gates/forms.py
from django import forms
from django.forms.formsets import formset_factory
from .models import *


class CostForm(forms.ModelForm):
    class Meta:
        model = Cost
        fields = Cost.get_form_fields()


class CostDetailForm(forms.ModelForm):
    class Meta:
        model = CostDetail
        fields = CostDetail.get_form_fields()

CostDetailFormSet = formset_factory(CostDetailForm)

gates/views.py
from django.contrib.auth import authenticate, decorators, login, logout
from django.core.urlresolvers import reverse_lazy
from django.http import Http404
from django.shortcuts import redirect, render, render_to_response
from django.views import generic
from django.template import RequestContext

# from django.contrib.auth.models import User
from .models import Group, Cost, CostDetail, Balance
from .forms import *
from django.contrib.auth.forms import UserCreationForm


class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return decorators.login_required(view)


class LoginView(generic.View):
    template_name = 'gates/login.html'

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            context = {}
            if 'next' in request.GET:
                context = {'next': request.GET['next']}
            return render(request, self.template_name, context)
        else:
            return redirect('/')

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            next_url = request.POST['next']
            if next_url == '':
                next_url = '/'
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(next_url)
                else:
                    context = {
                        'error_message': "Your account has been disabled.",
                        'next': next_url
                    }
            else:
                context = {
                    'error_message': "Invalid login.",
                    'next': next_url
                }
            return render(request, 'gates/login.html', context)
        else:
            return redirect('/')


class LogoutView(generic.View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            logout(request)
        return redirect('/accounts/login/')


class GroupListView(LoginRequiredMixin, generic.ListView):
    template_name = 'gates/index.html'
    context_object_name = 'group_list'

    def get_queryset(self):
        """
        Only display current logged in user's groups
        """
        return self.request.user.group_set.order_by('-creation_date')


class GroupDetailView(LoginRequiredMixin, generic.DetailView):
    model = Group
    template_name = 'gates/group.html'

    def get_context_data(self, **kwargs):
        context = super(GroupDetailView, self).get_context_data(**kwargs)
        # newer record at first
        cost_set = context['group'].cost_set.order_by('-creation_date')
        context['cost_set'] = cost_set
        return context

    def get(self, *args, **kwargs):
        object = super(GroupDetailView, self).get_object()
        if self.request.user in object.members.all():
            # only visiable to mebmers within the group
            return super(GroupDetailView, self).get(self, *args, **kwargs)
        else:
            # throw forbidden for non-member
            raise Http404()


class GroupCreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Group
    fields = Group.get_form_fields()
    template_name_suffix = '_create_form'

    def form_valid(self, form):
        r = super(GroupCreateView, self).form_valid(form)
        self.object.members.add(self.request.user)
        return r


class GroupUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    model = Group
    fields = Group.get_form_fields()
    template_name_suffix = '_update_form'


class GroupDeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = Group
    success_url = reverse_lazy('gates:index')


# class RecordCreateView(LoginRequiredMixin, generic.edit.CreateView):
#     model = Record
#     fields = Record.get_form_fields()
#     template_name_suffix = '_create_form'
#
#     def form_valid(self, form):
#         pid = self.kwargs['pid']
#         form.instance.group = self.request.user.group_set.get(pk=pid)
#         self.success_url = reverse_lazy('gates:group', kwargs={'pk': pid})
#         return super(RecordCreateView, self).form_valid(form)


def CostCreateView(request, pid):
    cost_form = CostForm(request.POST or None)
    CostDetailFormSet = formset_factory(CostDetailForm, extra=2, max_num=2)
    if request.POST and cost_form.is_valid():
        record = cost_form.save(commit=False)
        costdetail_formset = CostDetailFormSet(request.POST)
        if costdetail_formset.is_valid():
            record.save()
            costdetail_formset.save()
            return reverse_lazy('gates:group', kwargs={'pk': pid})
    else:
        costdetail_formset = CostDetailFormSet(request.POST or None)
    for c in costdetail_formset:
        print c

    return render_to_response(
        'gates/record_create_form.html',
        {
            'cost_form': cost_form,
            'costdetail_formset': costdetail_formset,
        },
        context_instance=RequestContext(request),
    )


class CostUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    model = Cost
    fields = Cost.get_form_fields()
    template_name_suffix = '_update_form'

    def get(self, *args, **kwargs):
        # check if the record belongs to the group
        # throw forbidden otherwise
        if self.kwargs['pid'] == str(self.get_object().group.pk):
            return super(CostUpdateView, self).get(self, *args, **kwargs)
        else:
            raise Http404()

    def post(self, *args, **kwargs):
        # check if the record belongs to the group
        # throw forbidden otherwise
        if self.kwargs['pid'] == str(self.get_object().group.pk):
            return super(CostUpdateView, self).post(self, *args, **kwargs)
        else:
            raise Http404()

    def form_valid(self, form):
        groupID = self.get_object().group.pk
        self.success_url = reverse_lazy('gates:group', kwargs={'pk': groupID})
        return super(CostUpdateView, self).form_valid(form)


class CostDeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = Cost

    def get(self, *args, **kwargs):
        # check if the record belongs to the group
        # throw forbidden otherwise
        if self.kwargs['pid'] == str(self.get_object().group.pk):
            return super(CostDeleteView, self).get(self, *args, **kwargs)
        else:
            raise Http404()

    def post(self, *args, **kwargs):
        # check if the record belongs to the group
        # throw forbidden otherwise
        groupID = self.get_object().group.pk
        if self.kwargs['pid'] == str(groupID):
            self.success_url = reverse_lazy(
                'gates:group', kwargs={'pk': groupID})
            return super(CostDeleteView, self).post(self, *args, **kwargs)
        else:
            raise Http404()

gates/templates/gates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <!-- Allow web app to be run in iOS full-screen mode. -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <!-- CSS files. -->
    <link rel="stylesheet" href="{% static 'gates/assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'gates/assets/css/bill-share.css' %}">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="global-headcolor"></div>
    <div class="container">
      {% block content %}{% endblock %}
      {% block footer %}
      <footer>
        <p class="text-center">© 2015 BillShare. Xiaoyu Tai, Zheng Yan, Yu Qiu.</p>
      </footer>
      {% endblock %}
    </div>
    <!-- JS files. -->
    <script src="{% static 'gates/assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'gates/assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'gates/assets/js/gravatar.js' %}"></script>
    {% if user %}
    <script type="text/javascript">
      var g = gravatar("{{ user.email }}", {size: 100, backup: "retro"});
      $(".global-avatar").attr("src", g);
    </script>
    {% endif %}
    {% block extrajs %}{% endblock %}
  </body>
</html>

gates/templates/gates/group.html
{% extends "gates/base.html" %}
{% load staticfiles %}
{% block title %}{{ group.name }} - BillShare{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-10 col-lg-offset-1">
    {% if error_message %}
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong>Error!</strong> {{ error_message }}
    </div>
    {% endif %}
    <div class="global-textheader">
      <div class="global-textheader-left">
        <h1>{{ group.name }}</h1>
      </div>
      <div class="global-textheader-right">
        <div class="dropdown">
          <a href="#" class="global-avatardiv dropdown-toggle" id="avatarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="global-avatar img-thumbnail">
          </a>
          <ul class="dropdown-menu" aria-labelledby="avatarDropdown">
            <li class="dropdown-header">{{ user.first_name }} {{ user.last_name }} (@{{ user.username }})</li>
            <li><a href="#">My Account</a></li>
            <li><a href="{% url 'gates:logout' %}">Log out</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="global-navbar">
      <p><a href="{% url 'gates:index' %}">My Groups</a> / {{ group.name }} <span class="group-navdesc">{{ group.desc }}</span></p>
    </div>
    <div class="group-copa">
      <h4>Costs and Payments</h4>
      <br /><br /><br /><br /><br />
      <h1 style="font-weight: 200;">TODO: add record, record list.</h1>
      <h1 style="font-weight: 800;">wait until cost/payment back-end is finished.</h1>
      <br /><br /><br /><br /><br />
    </div>
    <div class="group-memberlist">
      <h4>Members</h4>
      <div class="row">
      {% for member in group.members.all %}
        <div class="col-xs-3 col-sm-2 group-member">
          <a href="#" class="thumbnail">
            <img id="{{ member.id }}-avatar" class="group-members-avatar" src="{% static 'gates/assets/img/avatar-default.png' %}">
            <div class="caption">
              <p>{{ member.first_name }}<span class="hidden-xs"> {{ member.last_name }}</span></p>
            </div>
          </a>
        </div>
      {% endfor %}
        <div class="col-xs-3 col-sm-2 group-member">
          <a href="#" class="thumbnail group-newmember">
            <img id="{{ member.id }}-avatar" class="group-members-avatar" src="{% static 'gates/assets/img/avatar-add.png' %}">
            <div class="caption">
              <p>Invite<span class="hidden-xs"> others</span>?</p>
            </div>
          </a>
        </div>
      </div>
    </div>
    <div class="group-manage">
      <h4>Group Settings</h4>
    </div>
    <p>(<a href="{% url 'gates:group_update' group.id %}">Edit</a> / <a href="{% url 'gates:group_delete' group.id %}">Delete</a>) this group.</p>
  </div>
</div>

<!--
<h2>{{ group.name }}</h2>
<p>desc: {{ group.desc }}
<br/>creation_date: {{ group.creation_date }}
<br/>members: {{ group.members.all }}</p>
<p><a href="{% url 'gates:group_delete' group.id %}">delete this group?</a><p/>
<p><a href="{% url 'gates:cost_add' pid=group.id %}">Add a new record</a><p/>

{% if not record_set %}

<p>No records avaliable for this group yet.</p>

{% else %}

<table border>
    <thead>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>amount</th>
            <th>payer/receiver</th>
            <th>date</th>
            <th>last change</th>
            <th>note</th>
            <th>delete</th>
        </tr>
    </thead>
    <tbody>
    {% for record in cost_set %}
        <tr>
            <th>{{ record.id }}</th>
            <th><a href="{% url 'gates:cost_update' pid=group.id pk=record.id %}">{{ record.name }}</a></th>
            <td>{{ record.amount }}</td>
            <td>{{ record.payer }}/{{ record.receiver }}</td>
            <td>{{ record.creation_date }}</td>
            <td>{{ record.last_change_date }}</td>
            <td>{{ record.note }}</td>
            <th><a href="{% url 'gates:cost_delete' pid=group.id  pk=record.id %}">delete?</a></th>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endif %}
-->
{% endblock %}
{% block footer %}
  <footer>
    <p class="group-creationdate text-center"><b>{{ group.name }}</b> was create on {{ group.creation_date }}</p>
    <p class="text-center">© 2015 BillShare. Xiaoyu Tai, Zheng Yan, Yu Qiu.</p>
  </footer>
{% endblock %}
{% block extrajs %}
<script type="text/javascript">
  {% for member in group.members.all %}
  var g = gravatar("{{ member.email }}", {size: 278, backup: "retro"});
  $("#{{ member.id }}-avatar").attr('src', g);
  {% endfor %}
</script>
{% endblock %}

gates/templates/gates/group_confirm_delete.html
{% extends "gates/base.html" %}

{% block title %}Deleting {{ object.name }} - BillShare{% endblock %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

gates/templates/gates/group_create_form.html
{% extends "gates/base.html" %}

{% block title %}Creating a Group - BillShare{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-10 col-lg-offset-1">
    {% if error_message %}
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong>Error!</strong> {{ error_message }}
    </div>
    {% endif %}
    <div class="global-textheader">
      <div class="global-textheader-left">
        <h1>BillShare</h1>
      </div>
      <div class="global-textheader-right">
        <div class="dropdown">
          <a href="#" class="global-avatardiv dropdown-toggle" id="avatarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="global-avatar img-thumbnail">
          </a>
          <ul class="dropdown-menu" aria-labelledby="avatarDropdown">
            <li class="dropdown-header">{{ user.first_name }} {{ user.last_name }} (@{{ user.username }})</li>
            <li><a href="#">My Account</a></li>
            <li><a href="{% url 'gates:logout' %}">Log out</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="global-navbar">
      <p><a href="{% url 'gates:index' %}">My Groups</a> / Creating a Group</p>
    </div>
    <br />
    <br />
    <br />
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <form action="" method="post">
          {% csrf_token %}
          <p>
            <label class="control-label" for="id_name">Group name:</label>
            <input id="id_name" class="form-control input-lg" maxlength="100" name="name" type="text">
          </p>
          <p>
            <label class="control-label" for="id_desc">Group description:</label>
            <input id="id_desc" class="form-control input-lg" maxlength="200" name="desc" type="text">
          </p>
          <br />
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <input type="submit" class="btn btn-primary btn-lg btn-block" value="Create">
            </div>
          </div>
        </form>
      </div>
    </div>
    <br />
    <br />
    <br />
  </div>
</div>
{% endblock %}

gates/templates/gates/group_update_form.html
{% extends "gates/base.html" %}

{% block title %}Editing {{ group.name }} - BillShare{% endblock %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
<a href="{% url 'gates:group_delete' group.id %}">delete?</a>
{% endblock %}

gates/templates/gates/index.html
{% extends "gates/base.html" %}

{% block title %}My Groups - BillShare{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-10 col-lg-offset-1">
    {% if error_message %}
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong>Error!</strong> {{ error_message }}
    </div>
    {% endif %}
    <div class="global-textheader">
      <div class="global-textheader-left">
        <h1>BillShare</h1>
      </div>
      <div class="global-textheader-right">
        <div class="dropdown">
          <a href="#" class="global-avatardiv dropdown-toggle" id="avatarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img class="global-avatar img-thumbnail">
          </a>
          <ul class="dropdown-menu" aria-labelledby="avatarDropdown">
            <li class="dropdown-header">{{ user.first_name }} {{ user.last_name }} (@{{ user.username }})</li>
            <li><a href="#">My Account</a></li>
            <li><a href="{% url 'gates:logout' %}">Log out</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="global-navbar">
      <p></p>
    </div>
    <div class="index-grouplist row">
    {% if group_list %}
      {% for group in group_list %}
      <a href="{% url 'gates:group' group.id %}">
        <div class="index-group col-md-4 col-sm-6">
          <div class="index-groupinner text-center">
            <p class="index-groupicon"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></p>
            <h2>{{ group.name }}</h2>
            <p>{% for member in group.members.all %}
              {% if forloop.last %}
                {{ member.first_name }}
              {% else %}
                {{ member.first_name }},
              {% endif %}
            {% endfor %}</p>
          </div>
        </div>
      </a>
      {% endfor %}
      <a href="{% url 'gates:group_add'%}">
        <div class="index-group col-md-4 col-sm-6">
          <div class="index-groupinner index-groupadd text-center">
            <p class="index-groupicon"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></p>
            <h2>New Group?</h2>
            <p>Create your own group and invite others!</p>
          </div>
        </div>
      </a>
    {% else %}
      <a href="{% url 'gates:group_add'%}">
        <div class="index-group col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
          <div class="index-groupinner index-groupadd text-center">
            <p class="index-groupicon"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></p>
            <h2>Create a Group</h2>
            <p>Create your own group and invite others!</p>
          </div>
        </div>
      </a>
    {% endif %}
    </div>
  </div>
</div>
{% endblock %}

gates/templates/gates/login.html
{% extends "gates/base.html" %}

{% block title %}Log in - BillShare{% endblock %}

{% block content %}
<!-- CSS override -->
<style type="text/css">
.global-headcolor{
  height: 268px;
  margin: 0 0 -268px;
  background-color: #337ab7;
}
.login-textheader h1,
.login-textheader h4{
  color: #fff;
}
</style>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3 login-outterdiv">
    {% if error_message %}
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong>Error!</strong> {{ error_message }}
    </div>
    {% endif %}
    <form method="post" action="{% url 'gates:login' %}">
      {% csrf_token %}
      <div class="login-textheader global-textheader text-center">
        <h1>BillShare</h1>
        <h4>Welcome back!</h4>
      </div>
      <br/><br/><br/><br/>
      <input type="text" class="form-control input-lg" placeholder="username" name="username" id="username">
      <div class="input-group input-group-lg login-inputgroup">
        <input type="password" class="form-control" placeholder="secret" name="password" id="password">
        <span class="input-group-btn">
          <button class="btn btn-primary" type="submit" value="login">&gt;</button>
        </span>
      </div>
      <hr style="margin: 25px 0 20px;" />
      <div class="global-textheader text-center">
        <h4>New to BillShare?</h4>
        <a href="{% url 'gates:signup' %}">Sign up</a>
      </div>
      <hr />
      <input type="hidden" name="next" value="{{ next }}" />
    </form>
  </div>
</div>
{% endblock %}

gates/templates/gates/project_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

gates/templates/gates/project_create_form.html
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>

gates/templates/gates/signup.html
{% extends "gates/base.html" %}

{% block title %}Sign up - BillShare{% endblock %}

{% block content %}
<!-- CSS override -->
<style type="text/css">
.global-headcolor{
  height: 170px;
  margin: 0 0 -170px;
  background-color: #337ab7;
}
.signup-textheader h1,
.signup-textheader h4{
  color: #fff;
}
</style>
<div class="row">
  <div class="col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4 signup-outterdiv">
    <div class="global-textheader signup-textheader text-center">
      <h1>BillShare</h1>
      <h4>Welcome!</h4>
    </div>
    <br />
    <form method="post" action="{% url 'gates:signup' %}">
    {% csrf_token %}
    {% load i18n widget_tweaks %}
    {% for field in form %}
      {% if field.errors %}
      <div class="form-group has-error">
        <label class="control-label signup-formtext" for="id_{{ field.name }}">{{ field.label }}</label>
        <div>
        {{ field|attr:"class:form-control" }}
          <span class="help-block">
            {% for error in  field.errors %}{{ error }}{% endfor %}
          </span>
        </div>
      </div>
      {% else %}
      <div class="form-group">
        <label class="control-label signup-formtext" for="id_{{ field.name }}">{{ field.label }}</label>
        <div>
          {{ field|attr:"class:form-control" }}
          {% if field.help_text %}
            <p class="help-block"><small>{{ field.help_text }}</small></p>
          {% else %}
            <p class="help-block"><small></small></p>
          {% endif %}
        </div>
      </div>
      {% endif %}
    {% endfor %}
      <div class="form-group row">
        <div class="col-sm-offset-2 col-sm-8">
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </div>
      </div>
      <input type="hidden" name="next" value="" />
      <div class="global-textheader text-center">
        <hr />
        <h4>Have an account?</h4>
        <a href="{% url 'gates:login' %}">Log in</a>
      </div>
    </form>
    <hr />
  </div>
</div>
{% endblock %}